[package]
name = "rust-registry-index"
version = "0.1.0"
authors = ["lmn <leo.baldelli@outlook.com>"]
edition = "2018"

[dependencies]
warp = "0.3"
clap = "2.26"
glob = "0.3"
pretty_env_logger = "0.3"